<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d0f5b412-f18b-4d35-b60f-e538129a23f5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.82.1" />
    <PackageReference Include="Microsoft.PowerBI.Api" Version="5.0.0" />
	 
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mgt.Lit.Core\Mgt.Lit.Core.csproj" />
  </ItemGroup>

</Project>
